### ISSUE TITLE
Unhandled Exception: HiveError: There is already a TypeAdapter for typeId 

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/whats_for_dinner#7]
E/flutter (25570): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: There is already a TypeAdapter for typeId 2.
E/flutter (25570): #0      TypeRegistryImpl.registerAdapter (package:hive/src/registry/type_registry_impl.dart:104:11)
E/flutter (25570): #1      PersistStorage._allRecipeStorage (package:whats_for_dinner/model/persistStorage.dart:28:10)
E/flutter (25570): #2      PersistStorage.deleteAllRecipe (package:whats_for_dinner/model/persistStorage.dart:80:44)
E/flutter (25570): #3      _HomeScreenState.build.<anonymous closure> (package:whats_for_dinner/screen/homeScreen.dart:94:26)
E/flutter (25570): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (25570): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (25570): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter (25570): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (25570): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (25570): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
E/flutter (25570): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
E/flutter (25570): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
E/flutter (25570): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
E/flutter (25570): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
E/flutter (25570): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
E/flutter (25570): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (25570): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (25570): #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
E/flutter (25570): #18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (25570): #19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (25570): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (25570): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (25570): #22     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (25570): #23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (25570): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (25570): #25     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (25570): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (25570): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

-----------------------------------------------------------------------------------------------------------------------------------
Hive 관련 코드를 빼서 PersistStorage라는 클래스에 만들어 주고있다.

hive box에 있는 모든 데이터가 지워지도록 하는 버튼이 있다.
버튼을 누르면 

deleteRecipe(int index)
```
  Future<void> deleteRecipe(int index) async {
    final Box<Recipe> localStorage = await _allRecipeStorage;
    try {
      await localStorage.deleteAt(index);
    } catch (e) {
      log("레시피를 삭제하는데 에러가 발생했습니다. persisStorage.dart/deleteRecipe 메소드");
    }
  }
```
이 호출되고

_allRecipeStorage
```
  Future<Box<Recipe>> get _allRecipeStorage async {
    Hive.registerAdapter(RecipeAdapter()); //custom Object를 저장하기위해. type 등록
    Box<Recipe> allRecipeStorage = await Hive.openBox<Recipe>('recipeBox');
    return allRecipeStorage;
  }
```
가 호출된다.

이 부분에서
`Hive.registerAdapter(RecipeAdapter()); `
가 1번만 호출되도록 코드를 수정해야겠다.

**Comment by kangsudal** [comment]
테스트 이후에
되돌려줘야할것
-openBox에서 box이름: recipeBox ->새로바꾼이름
-Hive.registerAdapter 코드 위치


class의 property를 만들지말지 고민중
(Future<Box<Recipe>> get _allRecipeStorage가 있으면 굳이 없어도 되지않나?? 하지만 계속 openBox를 하는것이 옳을까? reference를 저장해주는 property가 있는게 좋은가?)
dart의

private와 public에 대해 읽어보기
https://duzi077.tistory.com/294
https://papabee.tistory.com/45

 getter와 setter에 대해 읽어보기
https://dev.to/newtonmunene_yg/dart-getters-and-setters-1c8f
https://www.geeksforgeeks.org/getter-and-setter-methods-in-dart/
https://eunjin3786.tistory.com/273

**Comment by kangsudal** [comment]
> 테스트 이후에 되돌려줘야할것 -openBox에서 box이름: recipeBox ->새로바꾼이름 -Hive.registerAdapter 코드 위치
> 
> class의 property를 만들지말지 고민중 (Future<Box> get _allRecipeStorage가 있으면 굳이 없어도 되지않나?? 하지만 계속 openBox를 하는것이 옳을까? reference를 저장해주는 property가 있는게 좋은가?) dart의
> 
> private와 public에 대해 읽어보기 https://duzi077.tistory.com/294 https://papabee.tistory.com/45
> 
> getter와 setter에 대해 읽어보기 https://dev.to/newtonmunene_yg/dart-getters-and-setters-1c8f https://www.geeksforgeeks.org/getter-and-setter-methods-in-dart/ https://eunjin3786.tistory.com/273


https://brunch.co.kr/@mystoryg/126
https://brunch.co.kr/@mystoryg/127
https://dart.dev/guides/language/language-tour#getters-and-setters

dart 공식문서에 Rectangle class의 double right와같이
Future<Box> get _allRecipeStorage 자체가 property(instance variable)다.
